### ISSUE TITLE
SEFS: Отчет об ошибке 

### ISSUE THREAD

**Issue by NDRAEY** [pimnik98/SayoriSDK#13]
Очень большие файлы не держит, типо DUKE картинки, раньше когда была только одна картинка Jump.duke и она отображалась нормально, но как добавил вторую картинку Wallpaper.duke при просмотре первой картинки появляется полоса в 17 пикселей с рандомными цветами и это я думаю и есть проблема которая появилась случайно. Я завтра посмотрю ещё потыкаю SEFS.

**Comment by pimnik98** [comment]
Может проблема с форматами PNG?

Проблема также наблюдается в другом файле, 
[Error](https://github.com/pimnik98/SayoriSDK/blob/main/Tools/Create%20RamDisk/SEFS/initrd/var/img/error.png) но в [QRCode](https://github.com/pimnik98/SayoriSDK/blob/main/Tools/Create%20RamDisk/SEFS/initrd/var/img/qrcode.png) проблема не наблюдается

**Comment by NDRAEY** [comment]
Проблема в загрузке в SayoriOS

**Comment by NDRAEY** [comment]
Проблема с памятью
